# Generated by Django 6.0.5 on 2026-05-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('serial_no', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('usi_kks_code', models.CharField(blank=True, max_length=100, null=True)),
                ('current_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(default='Draft', max_length=30)),
                ('status_code', models.CharField(default='05', max_length=5)),
                ('confidential', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('revision_due', models.DateTimeField(blank=True, null=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_for_deletion', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by_id', models.IntegerField(blank=True, null=True)),
                ('custom_metadata', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('dms_enabled', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('auth_codes', models.CharField(blank=True, default='', max_length=500)),
                ('hashed_password', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sso_user', models.BooleanField(default=False)),
                ('sso_name_id', models.CharField(blank=True, max_length=300, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'db_table': 'alert_logs',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_format', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.document')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'document_files',
            },
        ),
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.document')),
                ('target', models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='api.document')),
            ],
            options={
                'db_table': 'document_references',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('auth_required', models.BooleanField(default=False)),
                ('auth_code', models.CharField(blank=True, default='', max_length=100)),
                ('metadata_schema', models.JSONField(default=dict)),
                ('number_pattern', models.CharField(default='{CODE}-{YEAR}-{SEQ}', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.documenttype')),
            ],
            options={
                'db_table': 'document_types',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(db_column='doc_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.documenttype'),
        ),
        migrations.CreateModel(
            name='DocTypeFileFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_type', models.ForeignKey(db_column='doc_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.documenttype')),
            ],
            options={
                'db_table': 'doc_type_file_formats',
            },
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('lead_days', models.CharField(default='30,15,7', max_length=50)),
                ('notify_author', models.BooleanField(default=True)),
                ('notify_roles', models.CharField(blank=True, default='', max_length=200)),
                ('doc_type', models.OneToOneField(db_column='doc_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.documenttype')),
            ],
            options={
                'db_table': 'alert_configs',
            },
        ),
        migrations.CreateModel(
            name='NumberReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usi_kks', models.CharField(blank=True, max_length=100, null=True)),
                ('range_start', models.IntegerField()),
                ('range_end', models.IntegerField()),
                ('label', models.CharField(default='RESERVED', max_length=50)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.ForeignKey(db_column='doc_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.documenttype')),
                ('reserved_by', models.ForeignKey(db_column='reserved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'number_reservations',
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.document')),
                ('file', models.ForeignKey(db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.documentfile')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'file_access_logs',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('is_major', models.BooleanField(default=False)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('change_label', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.document')),
                ('created_by', models.ForeignKey(db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'document_versions',
            },
        ),
        migrations.CreateModel(
            name='DocumentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.document')),
                ('tagged_user', models.ForeignKey(blank=True, db_column='tagged_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_tagged', to='api.user')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_given', to='api.user')),
            ],
            options={
                'db_table': 'document_feedback',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, db_column='checked_out_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_docs', to='api.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_docs', to='api.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='responsible_person',
            field=models.ForeignKey(blank=True, db_column='responsible_person_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_docs', to='api.user'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='api.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('delivered', models.BooleanField(default=False)),
                ('alert_log', models.ForeignKey(db_column='alert_log_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.alertlog')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'alert_recipients',
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.JSONField(default=list)),
                ('doc_type', models.OneToOneField(db_column='doc_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.documenttype')),
            ],
            options={
                'db_table': 'workflow_configs',
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=20)),
                ('rejected_at_stage', models.CharField(blank=True, max_length=30, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=30, null=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'db_table': 'workflow_history_snapshots',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='Auto Populate', max_length=30)),
                ('stage', models.CharField(default='Prepare', max_length=30)),
                ('current_step', models.IntegerField(default=1)),
                ('total_steps', models.IntegerField(default=4)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='api.document')),
            ],
            options={
                'db_table': 'workflow_instances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=30)),
                ('checklist_required', models.BooleanField(default=False)),
                ('checklist_items', models.JSONField(default=list)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('checklist_template_path', models.CharField(blank=True, max_length=500, null=True)),
                ('checklist_template_name', models.CharField(blank=True, max_length=300, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_levels',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('checklist_done', models.BooleanField(default=False)),
                ('checklist_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('checklist_file_name', models.CharField(blank=True, max_length=300, null=True)),
                ('digital_sig_log', models.JSONField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(db_column='assignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wf_tasks', to='api.user')),
                ('level', models.ForeignKey(db_column='level_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.workflowlevel')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_tasks',
                'ordering': ['step'],
            },
        ),
    ]
