# Generated by Django 6.0.5 on 2026-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fix_doc_numbers_project_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_structure_folder',
            field=models.BooleanField(default=False),
        ),
    ]
