# Generated by Django 6.0.5 on 2026-05-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documenttype_is_structure_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='extra_parents',
            field=models.ManyToManyField(blank=True, related_name='extra_children', to='api.documenttype'),
        ),
    ]
