# Generated by Django 6.0.5 on 2026-05-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documenttype_extra_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_folders', to='api.user')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.userfolder')),
            ],
            options={
                'db_table': 'user_folders',
            },
        ),
        migrations.CreateModel(
            name='UserFolderDocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.ForeignKey(db_column='doc_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.documenttype')),
                ('folder', models.ForeignKey(db_column='folder_id', on_delete=django.db.models.deletion.CASCADE, to='api.userfolder')),
            ],
            options={
                'db_table': 'user_folder_doc_types',
                'unique_together': {('folder', 'doc_type')},
            },
        ),
        migrations.AddField(
            model_name='userfolder',
            name='doc_types',
            field=models.ManyToManyField(blank=True, related_name='pinned_in_folders', through='api.UserFolderDocType', to='api.documenttype'),
        ),
    ]
