# Generated by Django 6.0.5 on 2026-05-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userfolder_userfolderdoctype_userfolder_doc_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_by',
            field=models.ForeignKey(blank=True, db_column='archived_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_docs', to='api.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='obsolete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='purpose',
            field=models.CharField(default='release', max_length=20),
        ),
    ]
