# Generated by Django 6.0.5 on 2026-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_document_archived_at_document_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_docs', to='api.user'),
        ),
    ]
