# Generated by Django 6.0.5 on 2026-05-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_document_editors'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, db_column='decided_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_decided', to='api.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='api.document')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_made', to='api.user')),
            ],
            options={
                'db_table': 'edit_access_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
