# Generated by Django 6.0.4 on 2026-06-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_document_on_behalf_of_approverconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfolder',
            name='folder_manager',
            field=models.ForeignKey(blank=True, db_column='folder_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_folders', to='api.user'),
        ),
        migrations.CreateModel(
            name='FolderAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('UPLOAD', 'Upload')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='api.userfolder')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_access_requests', to='api.user')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_reviewed', to='api.user')),
            ],
            options={
                'db_table': 'folder_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('UPLOAD', 'Upload')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.userfolder')),
                ('granted_by', models.ForeignKey(blank=True, db_column='granted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to='api.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='api.user')),
            ],
            options={
                'db_table': 'folder_permissions',
                'unique_together': {('folder', 'user')},
            },
        ),
    ]
